# Generated by Django 3.2.7 on 2021-10-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('adID', models.AutoField(primary_key=True, serialize=False)),
                ('adName', models.CharField(max_length=20)),
                ('adPhoto', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Advisor',
            },
        ),
    ]
