# Generated by Django 3.2.7 on 2021-10-23 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisor',
            name='adPhoto',
            field=models.ImageField(default='', upload_to='media'),
        ),
    ]
