# Generated by Django 3.2.7 on 2021-10-24 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_alter_advisor_adphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('usrID', models.AutoField(primary_key=True, serialize=False)),
                ('usrName', models.CharField(max_length=20)),
                ('usrEmail', models.CharField(max_length=20)),
                ('usrPassword', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'User',
            },
        ),
    ]
