# Generated by Django 3.2.7 on 2021-10-25 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('bookID', models.AutoField(primary_key=True, serialize=False)),
                ('bookAdID', models.IntegerField()),
                ('bookAdName', models.CharField(max_length=20)),
                ('bookAdPhoto', models.ImageField(default='', upload_to='booking')),
                ('bookTime', models.DateTimeField()),
            ],
            options={
                'db_table': 'Booking',
            },
        ),
        migrations.AlterField(
            model_name='advisor',
            name='adPhoto',
            field=models.ImageField(default='', upload_to='advisor'),
        ),
    ]
