# Generated by Django 3.2.7 on 2021-10-25 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_auto_20211025_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='bookUsrID',
            field=models.IntegerField(default=0),
        ),
    ]
